---
channels:
    1:
        active: true
        color: FFFFFF
        end: 65535.0
        label: Phase
        max: 65535.0
        min: 0.0
        start: 3500.0
    2:
        active: true
        color: 00FF00
        end: 500.0
        label: Fluorescence
        max: 65535.0
        min: 0.0
        start: 200.0
greyscale: false
t: 1
version: 2
z: 1
